### ISSUE TITLE
Closure vs callable

### ISSUE THREAD

**Issue by veewee** [azjezz/psl#329]
**Describe the bug**
In V2, callables got replaces by Closure types all over the place.
I don't think this is a good idea.

Given following example:

```php
Fun\pipe(
   new InvokableClass()
)
```

This will result in:

```
 Uncaught TypeError: Psl\Fun\pipe(): Argument #1 must be of type Closure, InvokableClass given
```

Even though this class is invokable (callable):

```php
class InvokableClass {
    public function __invoke(string $x): int
    {
        return 132;
    }
};
```

This is a quite common structure in my codebases. 
The only alternative is to use the new first-class callable operator, but It adds some unnecesary noise over the codebase.

Is there any reason why you prefer to use Closure over the more generic callable?

**Comment by azjezz** [comment]
There's multiple reasons for doing this, but i think we can revert this just for `Psl\Fun` component as it doesn't apply there if you see that it's okay.

The reason is that revolt-php scheduler doesn't accept callables, just Closures, this is because it's easier to weaken closures before adding them to the event loop where a reference to the object scope will be held for an unknown amount of time ( see https://github.com/amphp/amp/blob/v3/src/functions.php#L129 ).

I did the change across the project to be consistent ( that being one of the main goals of PSL ), but since we have our own scheduler wrapper ( `Psl\Async\Scheduler` ), we can convert any callable to a Closure, or a weak closure, however, that will lower performance, as we need to check every callback type, and i tried to minimize the runtime type checking in PSL 2.0 ( e.g: we no longer throw for invalid data types, we trust that the end user is using a static analysis, and is passing the correct arguments, e.g: non-empty-string, positive-int, int<2, 32> ... etc ).

I personally see this as okay, since creating closures from callables in user land is not that hard anymore in most cases ( first-class callable syntax ).

e.g!:

```
$a = [$this, 'foo']; // 8.0
$a = $this->foo(...); // 8.1

$a = [Foo::class, 'bar']; // 8.0
$a = Foo::bar(...); // 8.1

$a = 'Psl\Str\length'; // 8.0
$a = Str\length(...); // 8.1
```

I think the only inconvenient case is `new Invokable()` ( which translates to `(new Invokable())(...)` )

**Comment by veewee** [comment]
The downside of only accepting closures is that one has to change pretty much every place where they are now using callables to be able to upgrade and use V2.
I don't honestly see the gain in this.

Just to give an idea, we use invokables all over the place. We use it because PHP (currently) lacks the possibility to autoload functions. In one way, it solves the autloading issue. Besides that, we use it as higher order functions that can be injected in services through containers (which is highly convenient). We use these structures in combination with fun, vec/dict/iter (transformers, serializers, ...), result and possibly others. It allows us to establish functional patterns through classes. 

Wouldn't it make more sense to always accept callables and instead convert `$closure = $callable(...)` before sending it to the event loop? You don't really need to do a type check at that moment, since you can convert any callable (closures included) to a closure with this new syntax.If you use a closure already and apply (...) on it, it just returns the same reference, see:
https://3v4l.org/NOHi0#v8.1.1

However I don't know if that would be an issue for the weak reference things. 


That way, the code still remains BC with v1, consistent, with less imports, and easier to use by the end users.

**Comment by azjezz** [comment]
I don't think BC with v1 matters, there's so many BC breaks already ( stuff that wasn't deprecated in v1.9 as well ), so that is not really important, i wouldn't recommend trying to keep compatibility with both v1 and v2.

> $closure = $callable(...) before sending it to the event loop

This will lower performance, even if something is already a closure, doing `$closure = $closure(...)` takes time.

using first-class callable syntax will always be faster: https://3v4l.org/o2Bcp#v8.1.1

and in examples of a server / long running process, this matters, as it adds up quickly.

**Comment by veewee** [comment]
Interesting numbers!
If you have 100.000 closures, it takes 0.015s more to convert it to a closure. How many closures would a server / long running process pass to the event loop? Those will most likely be dynamically added, meaning this convertion is spread over the parts that dynamically add these?  These slow-downs will most likely be executed whilst some other part is waiting for IO to finish?

Just trying to find the impact on regular usage here.


So to summarize the types related part: do we agree on the following, or do you see it differently?

- Closures are more performant and required for the async component by the event loop.
- Callables are a better choice in pretty much all other situations - since it is a base type and not an implementation. Comparable with terable and Traversable.


You mention we shouldn't focus on the BC between 1 and 2 too much. I don't fully agree with that. Most bc breaks are subtle and won't affect the end user that much. A change like this could be very impactful, which requires a lot of work in downstream packages. In return of all this hard work, you get back a less flexible system.

**Comment by azjezz** [comment]
> These slow-downs will most likely be executed whilst some other part is waiting for IO to finish?

no always, assuming you are dealing with 10000 resources ( http connections, database connections, redis, filesystem, sub process ... etc), at all time, there's a resource ready to be dispatched, so doing something else, most likely means delaying another operation.

**Comment by veewee** [comment]
Ok, I thought it would only be necessary to convert to closure when something gets [scheduled](https://github.com/azjezz/psl/blob/2.0.x/src/Psl/Async/Scheduler.php). And that the amount of schedules would be quite ok.
