### ISSUE TITLE
Return value of `Psl\Str\trim()` must be of the type string, null returned

### ISSUE THREAD

**Issue by devnix** [azjezz/psl#409]
**Describe the bug**
Hi! We have recently caught the following error in production:
![image](https://github.com/azjezz/psl/assets/1777519/98a24718-5d57-473c-b330-0a370cea8960)

**To Reproduce**
I really tried to replicate it in order to add a test case, but I have not been able to replicate it as I don't have the complete data.

**Expected behavior**
It should return an empty string instead of a null. As `preg_replace` looks like it returns `array|string|null`, maybe a guard clause should work?

If you confirm that this could be a bug I can send a PR

**Comment by veewee** [comment]
It looks like your input is of some sort of binary format. So it might be possible that the `u` modifier that is being used crashes somehow.

It would make sense to use `Psl\Regex\replace` internally in `Str\trim`.
That one has protection against errors internally in `preg_replace`, which will make sure the result is never null (since that is an error result)

See:
* https://github.com/azjezz/psl/blob/next/src/Psl/Regex/replace.php
* https://github.com/azjezz/psl/blob/next/src/Psl/Regex/Internal/call_preg.php

However, since the preg_match fails, the expected outcome should still be some sort of exception and not an empty string.

**Comment by devnix** [comment]
> However, since the preg_match fails, the expected outcome should still be some sort of exception and not an empty string.

The input came literally from a `$_POST` param, I would not expect a trim failing with an exception there, but I'm not really sure what would be the best practice here

**Comment by veewee** [comment]
Looked a bit further and think it is a UTF-8 overlong issue with which the preg extension cannot deal.

More info:

* https://stackoverflow.com/questions/73700859/laravel-exception-1366-incorrect-string-value-xc0-xa7-xc0-xa22-for
* https://kevinboone.me/overlong.html?i=1
* https://stackoverflow.com/questions/60838769/how-are-overlong-utf-8-encodings-generated

I was ablo to reproduce it here:
https://3v4l.org/BjLiS

The error message of the preg extension is as followed:

> string(56) "Malformed UTF-8 characters, possibly incorrectly encoded"
See https://3v4l.org/M7f2e

So I can confirm it's a bug. From my point of view, there are 2 things to do:

1. Use `Psl\Regex\replace` internally to deal with preg errors
2. Decide how to recover from failure. We could either return the initial input or throw an exception. It might probably fail somewhere further down the line - inside your application - anyways. So it might make more sense to just throw and fail  hard? Since the payload is probably crafted espacially to break your app. On the other hand - regular PHP's trim just returns the invalid chars.


The same applies for functions:

* `Str\trim_left`
* `Str\trim_right`
* `Str\replace_ci`

**Comment by azjezz** [comment]
> anyways. So it might make more sense to just throw and fail hard? Since the payload is probably crafted espacially to break your app.

💯 i agree with this, it is really unlikely that you want to deal with "dirty" input such as this, throwing an exception would be the appropriate thing to do.

i believe we do use regex in few other functions as well.

> Use `Psl\Regex\replace` internally to deal with preg errors

if we are going to fail, i think there's no need to use `Psl\Regex` in this case as it adds an overhead.

**Comment by veewee** [comment]
> if we are going to fail, i think there's no need to use `Psl\Regex` in this case as it adds an overhead.

It does give you the reason of the failure (which sure beats `null`). Not sure if the overhead is so much more than regular regex? It only adds error handling right?

**Comment by devnix** [comment]
I'm starting some tests to cover these cases, but I'm not sure which exception should be expected. Would make sense to add a guard to all those methods to check that the utf8 is valid instead of trying to catch the error?
