### ISSUE TITLE
Promise API

### ISSUE THREAD

**Issue by azjezz** [azjezz/psl#66]
implement promises according to the [Promises/A+](https://promisesaplus.com/) open standard.

**Comment by veewee** [comment]
Promises sound nice as well, but there are many packages out there already... Does it make a lot of sense to implement it again from scratch (which is a lot of hard work) instead of using amphp or react promises and coroutines? (Which are quite nice and have the async event loops covered through multiple extensions with vanilla PHP callbacks etc.)

**Comment by azjezz** [comment]
I'm not really sure about this, the question should be: "does it make sense to have promises in a standard library", the issue is we cannot use Amphp, or ReactPHP here, as PSL should not have any dependencies except for PHP itself and core/bundled/external extensions ( we shouldn't rely on PECL extensions as well, see: https://www.php.net/manual/en/extensions.membership.php ). 🤔

**Comment by WyriHaximus** [comment]
As long as it has a `then` method we at @reactphp can support it. (Assuming you're wrapping it through our `resolve` function.)

**Comment by azjezz** [comment]
I believe guzzle does the same, so I'm closing this as `Psl\Result\ResultInterface` will have a `then` method ( see discussion at #65 ), which mean it can *act* as a promise to some extent.

**Comment by veewee** [comment]
Wow, that's nice! Did not know react could do that!

**Comment by WyriHaximus** [comment]
@veewee Yup, only thing is that we assume it is a pure promise with no side effects.
